# 项目项目名
spring:
  application:
    name: zuul

# 配置端口号
server:
  port: 7016

# 配置注册中心
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:7011/eureka/

# 配置zuul超时时间
zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 6000

  # 自定义路由规则
  routes:
    # 指定规则名
    api-a:
      # 指定转发路径
      path: /user/**
      # 指定上边路径访问的服务
      serviceId: user



# zuul使用ribbon做负载均衡 设置ribbon超时时间(要小于zuul超时时间)
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

